### ISSUE TITLE
Support signing in with Fingerprint Sensor―Chrome for Android

### ISSUE THREAD

**Issue by grzuy** [cedarcode/webauthn-rails-demo-app#31]
Conversation of this actually started here https://github.com/cedarcode/webauthn-ruby/issues/68

Support WebAuthn ceremonies with:

* Authenticator: Fingerprint Sensor
* User agent: Chrome for Android

Chromium Blog announcement: https://blog.chromium.org/2018/09/chrome-70-beta-shape-detection-web.html

**Comment by grzuy** [comment]
I wasn't able to get the Android Fingerprint request pop-up on "Chrome for Android 69"
I wasn't able to get the Android Fingerprint request pop-up on "Chrome for Android 70 (Beta)"
I was able to see the fingerprint pop-up on "Chrome for Android 71 (Dev)"

**Comment by sorah** [comment]
Kindly note: as of this writing,

- Chrome 70 (beta) requires `platform` authenticatorSelection https://www.w3.org/TR/2018/CR-webauthn-20180807/#dom-publickeycredentialcreationoptions-authenticatorselection
  - Chrome is avoiding showing system Touch ID dialog always to a user, they may need to use external authenticator and showing the system dialog may make a confuse. They're developing the dialog to ask preferred authenticator to user: https://crrev.com/c/1172912 https://crbug.com/873710 
- On Canary, we need  `--enable-features=WebAuthenticationUI` to enable dialog which enables Touch ID without `platform` authenticatorSelection.  https://crbug.com/847985
  - I'm looking forward to the UI rolls out...

**Comment by sorah** [comment]
oops, this is only for registration. If we call `navigator.credentials.get()` with Touch ID's credential ID, Chrome prompts for Touch ID.

I implemented "force platform authenticator (may enable Touch ID)" link on my app.... https://github.com/sorah/clarion/commit/1c76ba15a26606d2a4c35fc230500a300617db69

**Comment by sorah** [comment]
Aagh, These 2 comments are intended on https://github.com/cedarcode/webauthn-rails-demo-app/issues/32 ! 🙇‍♀️

**Comment by grzuy** [comment]
Moved @sorah comments to https://github.com/cedarcode/webauthn-rails-demo-app/issues/32, as requested.

**Comment by grzuy** [comment]
@bdewater I was able to successfully sign in to https://webauthn.herokuapp.com with:

* Android 9
* Chrome Beta 70.0.3538.46
* Phone Fingerprint Sensor via the native Android pop-up

That Chrome version was released few days ago, previous patch version didn't worked for me.

@bdewater Still not working for you?

**Comment by grzuy** [comment]
Great.

@bdewater Let us know in case not working for you. We can re-open this.

**Comment by bdewater** [comment]
It worked for me - in https://github.com/cedarcode/webauthn-rails-demo-app/pull/33#issuecomment-427591687 I figured out what went wrong.

**Comment by grzuy** [comment]
Cool, thanks for confirming :-)
